# Generated by Django 3.0.1 on 2020-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50, verbose_name='User name')),
                ('email', models.TextField(max_length=50, verbose_name='User email')),
                ('password', models.TextField(max_length=60, verbose_name='User Password')),
            ],
        ),
    ]
