# Generated by Django 3.0.1 on 2020-01-12 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('tittle', models.TextField(verbose_name='post discription')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(max_length=20, verbose_name='good name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentbook.User')),
            ],
        ),
    ]
