# Generated by Django 3.0.1 on 2020-01-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentbook', '0002_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tittle',
            new_name='discription',
        ),
    ]
